### ISSUE TITLE
Column Fields in the outer pop up box

### ISSUE THREAD

**Issue by LakshmiSwethaGavini** [ramyasaimullapudi/ItemStockTracker#16]
A table should get displayed involving columns if an item hovers on the outer pop-up box.
Columns include - Retailer, URL, Stock Status, Price.

c.c @ramyasaimullapudi

**Comment by LakshmiSwethaGavini** [comment]
issue#9 depicts the initial design of this feature.

**Comment by ramyasaimullapudi** [comment]
Done by #20
